image: docker:stable

stages:
  - release
  - scan

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2

services:
  - name: docker:dind

before_script:
  - apk add --no-cache curl jq python py-pip
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

dockerbuild:
  stage: release
  script:
    # Cached version
    - docker pull ${CI_REGISTRY_IMAGE}:latest || true
    - docker build --cache-from ${CI_REGISTRY_IMAGE}:latest --tag ${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG} --tag ${CI_REGISTRY_IMAGE}:latest .
    - docker push ${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}
    - docker push ${CI_REGISTRY_IMAGE}:latest

    # Working but slow
#    - docker build -t ${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG} .
#    - docker tag ${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG} ${CI_REGISTRY_IMAGE}:latest
#    - docker push ${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}
#    - docker push ${CI_REGISTRY_IMAGE}:latest
  only:
    - tags
  tags:
    - docker

triggerscan:
  variables:
#    CI_DEBUG_TRACE: "true"
    POLL_INTERVAL: 2
    POLL_RETRIES: 150
  stage: scan
  script:
    - echo "Adding image to Smart Check engine at ${DSSC_SERVICE}"
    # Get bearer token from Smart Check
    - TOKEN=$(curl -sk -X POST $DSSC_SERVICE/api/sessions -H 'content-type:application/json' -H 'x-argus-api-version:2017-10-16' -d '{"user":{"userid":"'$DSSC_USERNAME'","password":"'$DSSC_PASSWORD'"}}' | jq -r '.token')
    # Create scan
    - SCAN_ID=$(curl -sk -X POST $DSSC_SERVICE/api/scans -H 'authorization:Bearer '$TOKEN -H 'cache-control:no-cache' -H 'content-type:application/json' -H 'x-argus-api-version:2017-11-15' -d '{"name":"test","source":{"type":"docker","registry":"'$CI_REGISTRY'","repository":"'$CI_PROJECT_PATH'","tag":"latest","credentials":{"username":"'$CI_REGISTRY_USER'","password":"'$CI_REGISTRY_TOKEN'"}}}}' | jq -r '.id')
    # Wait for scan completed
    - echo "Waiting for analysis to complete"
    - STATUS=""
    - RETRIES="1"
    - while [ "$STATUS" != "completed-with-findings" -a "$STATUS" != "completed-no-findings" -a "$STATUS" != "failed" -a "$RETRIES" -le "$POLL_RETRIES" ] ; do sleep $POLL_INTERVAL ; echo -n "." ; RETRIES=$(($RETRIES+1)) ; STATUS=$(curl -sk -H 'authorization:Bearer '$TOKEN'' -H 'content-Type:application/vnd.com.trendmicro.argus.webhook.v1+json' $DSSC_SERVICE/api/scans/$SCAN_ID | jq -r '.status') ; done
    # Analyse scan results
    # Pass if no Defcon1, critical, high or malware has been found
    - echo "Get scan results"
    - REPORT=$(curl -sk -H 'authorization:Bearer '$TOKEN'' -H 'content-Type:application/vnd.com.trendmicro.argus.webhook.v1+json' $DSSC_SERVICE/api/scans/$SCAN_ID | jq '{unresolved:.findings.vulnerabilities.unresolved, malware:.findings.malware}')
    - REPORT_FULL=$(curl -sk -H 'authorization:Bearer '$TOKEN'' -H 'content-Type:application/vnd.com.trendmicro.argus.webhook.v1+json' $DSSC_SERVICE/api/scans/$SCAN_ID)
    - CRITICALITY=$(echo $REPORT | jq -r '(.unresolved | (0 + .defcon1 + .critical + .high)) + (.malware)')
    - echo $REPORT
    - echo $CRITICALITY
    - echo $CRITICALITY > criticality
    - echo $REPORT_FULL > gl-container-scanning-report.json
    # Stop pipeline when CRITICALITY > 0
  artifacts:
    paths:
      - gl-container-scanning-report.json
      - criticality
  only:
    - tags
  tags:
    - docker
